# Routes builds to run on Trusty
# See using docker in builds: https://docs.travis-ci.com/user/docker/
sudo: required
services:
  - docker

language: ruby

before_script:
  - sudo modprobe ip_tables

script:
  # Configure binfmt-support on the Docker host
  # See https://github.com/multiarch/alpine
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  # Build image
  - docker build -t ljishen/pivpn:armv7hf . -f armv7hf/Dockerfile

  # Test image
  # Export the env TINI_SUBREAPER to fix the warning from tini:
  # [WARN  tini (23)] Tini is not running as PID 1 and isn't registered as a child subreaper.
  - docker run -ti --rm
      --privileged
      -p 443:443/udp
      -v "$HOME"/ovpns:/home/pivpn/ovpns
      -e TINI_SUBREAPER=true
      ljishen/pivpn:armv7hf

after_success:
  # Push image
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      docker push ljishen/pivpn:armv7hf
    fi
